[workspace]
members = ["chef", "boot-protocol", "bootloader", "snail", "common"]
resolver = "3"

package.edition = "2024"
package.license = " GPL-3.0-or-later"
package.authors = ["Youssef Harmal"]

[workspace.dependencies]
snail = { path = "snail" }

[workspace.metadata.chef]
ovmf-source = "https://github.com/rust-osdev/ovmf-prebuilt/releases/download/edk2-stable202408.01-r1/edk2-stable202408.01-r1-bin.tar.xz"

install-bootloader = "/boot/efi/pentos.efi"
