[workspace]
members = [
    "pentos",
    "config",
    "system/kernel",
    "system/bootloader",
    "system/klib",
    "system/system",
    "system/boot-protocol",
    "fs/fs",
    "fs/block",
    "fs/gpt",
    "fs/fat32",
    "lib/x64",
    "lib/io",
    "lib/sync",
    "lib/crypto",
    "lib/elf",
    "lib/spinlocks",
    "lib/acpi",
    "lib/log-debugcon",
    "lib/utils",
    "lib/keys",
    "lib/console-font",
    "macros/klib-macros",
    "build-system/chef",
    "build-system/builder",
    "test",
    "user/lib/runtime",
    "user/core/init",
]
resolver = "3"

package.edition = "2024"
package.license = " GPL-3.0-or-later"
package.authors = ["Youssef Harmal"]

[workspace.dependencies]
# Chef dependencies
cargo_metadata = "0.23.1"
clap = { version = "4.6.1", features = ["derive"] }
colored = "3.1.1"
reqwest = { version = "0.13.2", features = ["blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tar = "0.4.45"
xz = "0.1.0"
flate2 = "1.1.9"
md5 = "0.8.0"
getrandom = "0.4.2"
env_logger = "0.11.10"
tempfile = "3.27.0"

prettyplease = "0.2.37"
toml = "1.1.0"
syn = { version = "2.0.117", features = ["full"] }
quote = "1.0.45"
proc-macro2 = "1.0.106"

# Bootloader dependencies
uefi = { version = "0.37.0" }

# Logging system
# TODO: self-host this
log = "0.4.29"

# local crates
klib = { path = "system/klib" }
system = { path = "system/system" }
boot-protocol = { path = "system/boot-protocol" }

config = { path = "config" }

builder = { path = "build-system/builder" }

x64 = { path = "lib/x64" }
elf = { path = "lib/elf" }
spinlocks = { path = "lib/spinlocks" }
acpi = { path = "lib/acpi" }
utils = { path = "lib/utils" }
log-debugcon = { path = "lib/log-debugcon" }
keys = { path = "lib/keys" }
console-font = { path = "lib/console-font" }
io = { path = "lib/io" }
crypto = { path = "lib/crypto" }
sync = { path = "lib/sync" }

fs = { path = "fs/fs" }
block = { path = "fs/block" }
gpt = { path = "fs/gpt" }
fat32 = { path = "fs/fat32" }

# user space crates
runtime = { path = "user/lib/runtime" }

[workspace.metadata.chef]
ovmf-version = "edk2-stable202511-r1"
ovmf-source-template = "https://github.com/rust-osdev/ovmf-prebuilt/releases/download/$$/$$-bin.tar.xz"
ovmf-varsfd-path-template = "$$-bin/x64/vars.fd"
ovmf-codefd-path-template = "$$-bin/x64/code.fd"

font-version = "1.11.6"
font-source-template = "https://github.com/sunaku/tamzen-font/archive/refs/tags/Tamzen-$$.tar.gz"
font-path-template = "tamzen-font-Tamzen-$$/psf/TamzenForPowerline10x20.psf"

install-bootloader = "/boot/efi/pentos.efi"
install-kernel = "/boot/efi/pentos.kernel"

qemu-numcores = "12"
qemu-mem = "8G"
qemu-resolution = "1920x1080"
