[toolchain]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-uefi",
    "x86_64-unknown-none",
]
channel = "nightly-2026-03-01"
profile = "default"
components = ["rust-analyzer", "rust-src"]
