[toolchain]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-uefi",
    "x86_64-unknown-none",
]
channel = "nightly-2025-03-14" # PI day version
profile = "default"
components = ["rust-analyzer", "rust-src"]
