[package]
name = "fat32"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
config.workspace = true
block.workspace = true
io.workspace = true
sync.workspace = true
log.workspace = true
fs.workspace = true

[target.'cfg(not(target_os = "none"))'.dependencies]
getrandom.workspace = true
