[package]
name = "mman"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
x64.workspace = true
common.workspace = true
spinlocks.workspace = true