[package]
name = "kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
boot-protocol.workspace = true
x64.workspace = true

[build-dependencies]
builder.workspace = true
