[package]
name = "chef-dev"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
env_logger.workspace = true
log.workspace = true

md5.workspace = true

clap.workspace = true

tar.workspace = true

tempfile.workspace = true

chef-core.workspace = true


# local crates
block.workspace = true
gpt.workspace = true
io.workspace = true
fat32.workspace = true
fs.workspace = true
