[package]
name = "bootloader"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
log = "0.4.26"
uefi = { version = "0.34.1", features = ["logger"] }
