name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bootloader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-build-bootloader
      - name: Cache Toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Setup Build System
        run: make
      - name: Build Bootloader (Release)
        run: make build-release-bootloader
      - name: Upload Bootloader (Release)
        uses: actions/upload-artifact@v4
        with:
          name: bootloader-release
          path: target/uefi/release/bootloader.efi
      - name: Build Bootloader (Debug)
        run: make build-debug-bootloader
      - name: Upload Bootloader (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: bootloader-debug
          path: target/uefi/debug/bootloader.efi
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-build-kernel
      - name: Cache Toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Setup Build System
        run: make
      - name: Build Kernel (Release)
        run: make build-release-kernel
      - name: Upload Kernel (Release)
        uses: actions/upload-artifact@v4
        with:
          name: kernel-release
          path: target/kernel/release/kernel
      - name: Build Kernel (Debug)
        run: make build-debug-kernel
      - name: Upload Kernel (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: kernel-debug
          path: target/kernel/debug/kernel