name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-bootloader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm
      - name: Cache Cargo
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-build-bootloader
      - name: Cache Toolchain
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Build Bootloader (Release)
        run: cargo dev build -p release bootloader
      - name: Upload Bootloader (Release)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: bootloader-release
          path: target/uefi/release/bootloader.efi
      - name: Build Bootloader (Debug)
        run: cargo dev build -p debug bootloader
      - name: Upload Bootloader (Debug)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: bootloader-debug
          path: target/uefi/debug/bootloader.efi

  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm
      - name: Cache Cargo
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-build-kernel
      - name: Cache Toolchain
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Build Kernel (Release)
        run: cargo dev build -p release kernel
      - name: Upload Kernel (Release)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: kernel-release
          path: target/kernel/release/kernel
      - name: Build Kernel (Debug)
        run: cargo dev build -p debug kernel
      - name: Upload Kernel (Debug)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: kernel-debug
          path: target/kernel/debug/kernel

  build-img:
    runs-on: ubuntu-latest
    needs: [build-bootloader, build-kernel]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm mtools parted
      - name: Cache Cargo
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-build-img
      - name: Cache Toolchain
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Build Release Image
        run: cargo dev generate img disk -p release
      - name: Upload Release Image
        uses: actions/upload-artifact@v7.0.0
        with:
          name: pentos-release.img
          path: .build/release/img/pentos.img
      - name: Build Debug Image
        run: cargo dev generate img disk -p debug
      - name: Upload Debug Image
        uses: actions/upload-artifact@v7.0.0
        with:
          name: pentos-debug.img
          path: .build/debug/img/pentos.img