name: Docs & Pages
on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm
      - name: Cache Cargo
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-doc
      - name: Cache Toolchain
        uses: actions/cache@v5.0.3
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Generate Docs
        run: cargo dev doc
      - name: Upload Docs (ZIP)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: docs
          path: target/doc
      - name: Upload Docs (Pages)
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: doc
    steps:
      - name: Deploy Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4