name: Lint & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install nasm
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-lint
      - name: Cache Toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Setup Build System
        run: make
      - name: Lint
        run: make clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-test
      - name: Cache Toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rustup-${{ hashFiles('rust-toolchain.toml') }}
      - name: Setup Build System
        run: make
      - name: Run tests
        run: make test
